import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';

const UP=new THREE.Vector3(0,1,0);
const V=(p)=>new THREE.Vector3(p[0],p[2],-p[1]);
function seeded(n){return (Math.sin(n*127.1+311.7)*43758.5453)%1+.5;}
export function terrainHeight(city,x,n){const t=city.terrain,b=city.bounds,u=THREE.MathUtils.clamp((x-b.minX)/(b.maxX-b.minX)*(t.width-1),0,t.width-1.0001),v=THREE.MathUtils.clamp((n-b.minY)/(b.maxY-b.minY)*(t.height-1),0,t.height-1.0001);const i=Math.floor(u),j=Math.floor(v),a=u-i,c=v-j,h=t.heights;return THREE.MathUtils.lerp(THREE.MathUtils.lerp(h[j*t.width+i],h[j*t.width+i+1],a),THREE.MathUtils.lerp(h[(j+1)*t.width+i],h[(j+1)*t.width+i+1],a),c);}
function grainTexture(){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),d=ctx.createImageData(256,256);let s=31;for(let i=0;i<d.data.length;i+=4){s=(s*1664525+1013904223)>>>0;let v=120+(s%55);d.data[i]=d.data[i+1]=d.data[i+2]=v;d.data[i+3]=255;}ctx.putImageData(d,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(1,1);t.colorSpace=THREE.SRGBColorSpace;return t;}
function facadeTexture(type){const c=document.createElement('canvas');c.width=256;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=type==='glass'?'#526a73':'#deddd5';ctx.fillRect(0,0,256,256);for(let floor=0;floor<4;floor++){const y=floor*64;ctx.fillStyle=type==='glass'?'#334b54':'#c6c3b9';ctx.fillRect(0,y+59,256,5);for(let column=0;column<4;column++){const x=column*64;ctx.fillStyle='#f4f1e4';ctx.fillRect(x+14,y+9,35,45);ctx.fillStyle='#253d49';ctx.fillRect(x+17,y+12,29,38);ctx.fillStyle='#739299';ctx.fillRect(x+18,y+13,12,17);ctx.fillStyle='#a9aba1';ctx.fillRect(x+31,y+13,2,38);ctx.fillRect(x+17,y+31,29,2);ctx.fillStyle='#fff9df';ctx.fillRect(x+11,y+54,42,4);}}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;}
function meshGeometry(pos,uv=[]){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));if(uv.length)g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.computeVertexNormals();return g;}
function box(w,h,d,mat,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m;}

export class CityRenderer{
 constructor(canvas,city){this.city=city;this.scene=new THREE.Scene();this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;this.camera=new THREE.PerspectiveCamera(55,1,.1,3500);this.clock=0;this.mode=0;this.photo=false;this.orbit={yaw:.5,pitch:.3,distance:11};this.materials={};this.lightPosts=[];this.carVisuals=new Map();this.target=new THREE.Vector3();this.sun=new THREE.DirectionalLight('#ffe1af',3.2);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-100,right:100,top:100,bottom:-100,near:1,far:800});this.sun.shadow.normalBias=.35;this.sun.shadow.bias=-.0001;this.scene.add(this.sun,this.sun.target);this.ambient=new THREE.HemisphereLight('#c4dbf2','#6b7460',2);this.scene.add(this.ambient);const pmrem=new THREE.PMREMGenerator(this.renderer);this.scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();this.sky=new Sky();this.sky.scale.setScalar(450000);this.scene.add(this.sky);this.sky.material.uniforms.turbidity.value=4;this.sky.material.uniforms.rayleigh.value=1.5;this.sky.material.uniforms.mieCoefficient.value=.006;this.sky.material.uniforms.mieDirectionalG.value=.85;this.createWorld();this.createRain();this.setWeather('golden');this.resize();window.addEventListener('resize',()=>this.resize());}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 createWorld(){const city=this.city,t=city.terrain,b=city.bounds,grain=grainTexture();this.materials.ground=new THREE.MeshStandardMaterial({color:'#76816b',roughness:1,map:grain});this.materials.road=new THREE.MeshStandardMaterial({color:'#666a70',roughness:.92,map:grain});this.materials.sidewalk=new THREE.MeshStandardMaterial({color:'#b7b3a5',roughness:.95,map:grain});this.materials.line=new THREE.MeshStandardMaterial({color:'#e6d4a3',roughness:.8});this.materials.white=new THREE.MeshStandardMaterial({color:'#eee5d2',roughness:.7});this.materials.roof=new THREE.MeshStandardMaterial({color:'#7b807b',roughness:.9});const terrain=new THREE.PlaneGeometry(b.maxX-b.minX,b.maxY-b.minY,t.width-1,t.height-1);terrain.rotateX(-Math.PI/2);const pos=terrain.attributes.position;for(let i=0;i<pos.count;i++)pos.setY(i,terrainHeight(city,pos.getX(i),-pos.getZ(i))-.14);terrain.computeVertexNormals();const ground=new THREE.Mesh(terrain,this.materials.ground);ground.receiveShadow=true;this.scene.add(ground);
 const roadPositions=[],brickPositions=[],sidewalkPositions=[],linePositions=[],whitePositions=[];
 const ribbon=(a,b,width,out,lift=0)=>{const dx=b[0]-a[0],dy=b[1]-a[1],d=Math.hypot(dx,dy);if(d<.05)return;const nx=-dy/d*width/2,ny=dx/d*width/2;const v=[[a[0]+nx,a[2]+lift,-a[1]-ny],[a[0]-nx,a[2]+lift,-a[1]+ny],[b[0]+nx,b[2]+lift,-b[1]-ny],[b[0]-nx,b[2]+lift,-b[1]+ny]];for(const i of [0,1,2,1,3,2])out.push(...v[i]);};
 const roadEnds=new Map();for(const road of city.roads){for(let i=0;i<road.points.length-1;i++){const a=road.points[i],c=road.points[i+1];ribbon(a,c,road.width+2.8,sidewalkPositions,.06);ribbon(a,c,road.width,['bricks','brick','paving_stones','cobblestone'].includes(road.surface)?brickPositions:roadPositions,.1);if(road.width>=6&&!road.oneway){ribbon(a,c,.13,linePositions,.115);}else if(road.width>6&&i%3===0){const mid=a.map((v,j)=>(v+c[j])/2);ribbon(a,mid,.12,whitePositions,.115);}}for(const p of [road.points[0],road.points.at(-1)]){const key=`${Math.round(p[0])},${Math.round(p[1])}`;let e=roadEnds.get(key);if(!e)roadEnds.set(key,{p,w:road.width,count:1});else {e.count++;e.w=Math.max(e.w,road.width);}}}
 const add=(arr,mat,repeat)=>{if(!arr.length)return;const uv=[];for(let i=0;i<arr.length;i+=3)uv.push(arr[i]/repeat,arr[i+2]/repeat);const m=new THREE.Mesh(meshGeometry(arr,uv),mat);m.receiveShadow=true;this.scene.add(m);};add(sidewalkPositions,this.materials.sidewalk,3);add(roadPositions,this.materials.road,4);add(brickPositions,new THREE.MeshStandardMaterial({color:'#ac6c53',roughness:.85,map:grain}),.4);add(linePositions,this.materials.line,1);add(whitePositions,this.materials.white,1);
 // Junction disks close ribbon joins; painted crossings are restricted to actual junctions.
 const junctions=[];for(const e of roadEnds.values()){if(e.count<2)continue;const r=e.w/2;for(let k=0;k<16;k++){const a=k/16*Math.PI*2,c=(k+1)/16*Math.PI*2;junctions.push(e.p[0],e.p[2]+.105,-e.p[1],e.p[0]+Math.sin(a)*r,e.p[2]+.105,-e.p[1]+Math.cos(a)*r,e.p[0]+Math.sin(c)*r,e.p[2]+.105,-e.p[1]+Math.cos(c)*r);}}add(junctions,this.materials.road,4);
 const railPos=[];
 for(const rail of city.railways||[]){const gauge=(parseFloat(rail.tags?.gauge)||1067)/1000;for(let i=1;i<rail.points.length;i++){const a=rail.points[i-1],c=rail.points[i],dx=c[0]-a[0],dy=c[1]-a[1],d=Math.hypot(dx,dy);if(d<.01)continue;for(const side of [-1,1]){const nx=-dy/d*gauge/2*side,ny=dx/d*gauge/2*side;ribbon([a[0]+nx,a[1]+ny,a[2]],[c[0]+nx,c[1]+ny,c[2]],.085,railPos,.125);}}}add(railPos,new THREE.MeshStandardMaterial({color:'#7c898e',metalness:.9,roughness:.24}),1);
 this.createBuildings();this.createStreetFurniture();this.createBoundary();}
 createBuildings(){const facade=facadeTexture('house'),palette=['#d9cec2','#adb9b2','#d9c7ad','#c9d4d5','#c5b5a5','#e0d5b7','#b5bbc4','#bbcec3','#dac4b1'];const buckets=palette.map(()=>({wall:[],uv:[],roof:[]}));const roofPos=[];for(let bi=0;bi<this.city.buildings.length;bi++){const b=this.city.buildings[bi];let p=b.footprint;if(p.length<3)continue;if(Math.hypot(p[0][0]-p.at(-1)[0],p[0][1]-p.at(-1)[1])<.01)p=p.slice(0,-1);const bucket=buckets[bi%palette.length];let bottom=Math.min(...p.map(v=>v[2]))-.5,top=Math.max(...p.map(v=>v[2]))+b.height;const contour=p.map(v=>new THREE.Vector2(v[0],-v[1]));const holes=(b.footprintHoles||[]).map(h=>h.map(v=>new THREE.Vector2(v[0],-v[1])));const triangles=THREE.ShapeUtils.triangulateShape(contour,holes),all=[...contour,...holes.flat()];for(const tr of triangles){for(const ix of [tr[0],tr[2],tr[1]])roofPos.push(all[ix].x,top,all[ix].y);}for(const ring of [p,...(b.footprintHoles||[])]){for(let j=0;j<ring.length;j++){const a=ring[j],c=ring[(j+1)%ring.length],len=Math.hypot(c[0]-a[0],c[1]-a[1]);if(len<.1)continue;const verts=[[a[0],bottom,-a[1]],[c[0],bottom,-c[1]],[a[0],top,-a[1]],[c[0],top,-c[1]]],uv=[[0,0],[len/16,0],[0,(top-bottom)/13],[len/16,(top-bottom)/13]];for(const k of [0,1,2,1,3,2]){bucket.wall.push(...verts[k]);bucket.uv.push(...uv[k]);}}}}
 for(let i=0;i<buckets.length;i++){const b=buckets[i];if(!b.wall.length)continue;const mat=new THREE.MeshStandardMaterial({color:palette[i],map:facade,roughness:.83,side:THREE.DoubleSide});const m=new THREE.Mesh(meshGeometry(b.wall,b.uv),mat);m.castShadow=true;m.receiveShadow=true;this.scene.add(m);}const roof=new THREE.Mesh(meshGeometry(roofPos),this.materials.roof);roof.castShadow=true;roof.receiveShadow=true;roof.material.side=THREE.DoubleSide;this.scene.add(roof);}
 createStreetFurniture(){const poles=[],lights=[],treeTrunks=[],treeCrowns=[];const pmat=new THREE.MeshStandardMaterial({color:'#35484c',metalness:.6,roughness:.5});let count=0;for(const r of this.city.roads){let distance=0;for(let i=1;i<r.points.length;i++){const a=r.points[i-1],b=r.points[i],dx=b[0]-a[0],dy=b[1]-a[1],d=Math.hypot(dx,dy);distance+=d;if(distance<40||d<.01)continue;distance=0;const side=count++%2?1:-1,off=r.width/2+1.25,x=b[0]-dy/d*off*side,z=-b[1]-dx/d*off*side,y=terrainHeight(this.city,x,-z);const pg=new THREE.CylinderGeometry(.065,.11,7.5,6);pg.translate(x,y+3.75,z);poles.push(pg);const arm=new THREE.BoxGeometry(1.9,.08,.08);arm.translate(x+.7,y+7.4,z);poles.push(arm);const lg=new THREE.BoxGeometry(.65,.12,.28);lg.translate(x+1.5,y+7.35,z);lights.push(lg);this.lightPosts.push(new THREE.Vector3(x+1.5,y+7.1,z));if(count%3===0){const tg=new THREE.CylinderGeometry(.11,.18,3.5,5);tg.translate(x+3,y+1.75,z);treeTrunks.push(tg);const cg=new THREE.IcosahedronGeometry(1.5,1);cg.scale(1,1.5,1);cg.translate(x+3,y+4.3,z);treeCrowns.push(cg);}}}const combine=(gs,mat,cast=true)=>{if(gs.length){const g=mergeGeometries(gs),m=new THREE.Mesh(g,mat);m.castShadow=cast;m.receiveShadow=true;this.scene.add(m);gs.forEach(g=>g.dispose());return m;}};combine(poles,pmat);this.lampMat=new THREE.MeshStandardMaterial({color:'#fff0cc',emissive:'#ffcd8f',emissiveIntensity:0});combine(lights,this.lampMat,false);combine(treeTrunks,new THREE.MeshStandardMaterial({color:'#766551'}));combine(treeCrowns,new THREE.MeshStandardMaterial({color:'#536c4b',roughness:1}));this.nearLights=[];for(let i=0;i<5;i++){const light=new THREE.PointLight('#ffd39c',0,19,2);this.scene.add(light);this.nearLights.push(light);}}
 createBoundary(){const b=this.city.bounds,p=[];for(const [[ax,an],[bx,bn]] of [[[b.minX,b.minY],[b.maxX,b.minY]],[[b.maxX,b.minY],[b.maxX,b.maxY]],[[b.maxX,b.maxY],[b.minX,b.maxY]],[[b.minX,b.maxY],[b.minX,b.minY]]])for(let t=0;t<1;t+=.01){const x=THREE.MathUtils.lerp(ax,bx,t),n=THREE.MathUtils.lerp(an,bn,t);p.push(x,terrainHeight(this.city,x,n)+1,-n);}this.boundary=new THREE.Points(meshGeometry(p),new THREE.PointsMaterial({color:'#ffd39f',size:.3,transparent:true,opacity:.55}));this.scene.add(this.boundary);}
 createRain(){const positions=new Float32Array(1800*3);for(let i=0;i<positions.length;i+=3){positions[i]=(Math.random()-.5)*100;positions[i+1]=Math.random()*80;positions[i+2]=(Math.random()-.5)*100;}this.rain=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.BufferAttribute(positions,3)),new THREE.PointsMaterial({color:'#b9d4e2',size:.07,transparent:true,opacity:.55}));this.rain.visible=false;this.scene.add(this.rain);}
 createCar(color='#d19451',player=true){const root=new THREE.Group();const paint=new THREE.MeshPhysicalMaterial({color,metalness:.68,roughness:.24,clearcoat:1,clearcoatRoughness:.12});const rubber=new THREE.MeshStandardMaterial({color:'#141819',roughness:.9});const metal=new THREE.MeshStandardMaterial({color:'#ccd6d8',metalness:.9,roughness:.2});const dark=new THREE.MeshStandardMaterial({color:'#17222c',roughness:.55});const glass=new THREE.MeshPhysicalMaterial({color:'#426577',metalness:.3,roughness:.08,transparent:true,opacity:.83,clearcoat:1});const shell=new THREE.Mesh(new RoundedBoxGeometry(1.77,.44,4.25,3,.12),paint);shell.position.y=.22;shell.castShadow=true;root.add(shell);root.add(box(1.64,.17,1.25,paint,0,.44,-1.38));root.add(box(1.62,.18,.75,paint,0,.43,1.65));const cabinPos=[],vs=[[-.775,.45,-1.06],[.775,.45,-1.06],[-.69,.99,-.66],[.69,.99,-.66],[-.775,.45,1.2],[.775,.45,1.2],[-.69,.99,.72],[.69,.99,.72]];for(const i of [0,2,1,1,2,3,4,5,6,5,7,6,0,4,2,4,6,2,1,3,5,5,3,7])cabinPos.push(...vs[i]);glass.side=THREE.DoubleSide;const cabin=new THREE.Mesh(meshGeometry(cabinPos),glass);root.add(cabin);root.add(box(1.42,.085,1.42,paint,0,1.02,.03));
 for(const pair of [[vs[0],vs[2]],[vs[1],vs[3]],[vs[4],vs[6]],[vs[5],vs[7]]]){const a=new THREE.Vector3(...pair[0]),b=new THREE.Vector3(...pair[1]),strut=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,a.distanceTo(b),6),paint);strut.position.copy(a).add(b).multiplyScalar(.5);strut.quaternion.setFromUnitVectors(UP,b.sub(a).normalize());root.add(strut);}for(const x of [-.785,.785]){root.add(box(.035,.56,.09,paint,x,.7,.28));root.add(box(.07,.09,3.1,metal,x*1.08,.28,.24));root.add(box(.24,.1,.17,paint,x*1.24,.57,-.67));root.add(box(.07,.04,.2,metal,x*1.07,.52,.42));}
 root.add(box(1.68,.14,.12,dark,0,.09,-2.14));root.add(box(1.68,.12,.12,dark,0,.07,2.14));root.add(box(.75,.14,.025,new THREE.MeshStandardMaterial({color:'#e2e4d5'}),0,.16,2.212));const headmat=new THREE.MeshStandardMaterial({color:'#fff7e4',emissive:'#fff0cf',emissiveIntensity:2});const taillight=new THREE.MeshStandardMaterial({color:'#b32723',emissive:'#ff160c',emissiveIntensity:1});for(const x of [-.61,.61]){root.add(box(.42,.12,.04,headmat,x,.31,-2.16));root.add(box(.42,.1,.04,taillight,x,.32,2.16));}const wheelMeshes=[];for(let i=0;i<4;i++){const wheel=new THREE.Group();const tire=new THREE.Mesh(new THREE.CylinderGeometry(.335,.335,.23,20),rubber);tire.rotation.z=Math.PI/2;wheel.add(tire);const rim=new THREE.Mesh(new THREE.CylinderGeometry(.235,.235,.24,12),metal);rim.rotation.z=Math.PI/2;wheel.add(rim);for(let k=0;k<5;k++){const spoke=box(.25,.035,.45,dark);spoke.rotation.x=k/5*Math.PI;wheel.add(spoke);}tire.castShadow=true;this.scene.add(wheel);wheelMeshes.push(wheel);}const lamps=[];if(player)for(const x of [-.6,.6]){const lamp=new THREE.SpotLight('#fff0cf',0,75,.4,.5,1.5);lamp.position.set(x,.37,-2.12);lamp.target.position.set(x,-.3,-40);root.add(lamp,lamp.target);lamps.push(lamp);}const steering=new THREE.Mesh(new THREE.TorusGeometry(.18,.025,8,24),dark);steering.position.set(-.4,.6,-.54);root.add(steering);root.add(box(1.5,.18,.22,dark,0,.44,-.65));this.scene.add(root);return {root,wheels:wheelMeshes,paint,lamps,taillight,steering,cabin};}
 setWeather(mode){this.weather=mode;const cfg={golden:{sun:3.2,ambient:1.9,color:'#eed6b5',fog:.0011,elevation:9,azimuth:240,exposure:1},day:{sun:3.5,ambient:2.1,color:'#c8ddea',fog:.0009,elevation:48,azimuth:210,exposure:1},fog:{sun:.5,ambient:2.3,color:'#b0bdc0',fog:.0075,elevation:18,azimuth:250,exposure:1},rain:{sun:.45,ambient:1.8,color:'#7d929f',fog:.0045,elevation:16,azimuth:220,exposure:1},night:{sun:.03,ambient:.28,color:'#0c1828',fog:.002,elevation:-8,azimuth:260,exposure:1.25}}[mode];this.cfg=cfg;this.scene.fog=new THREE.FogExp2(cfg.color,cfg.fog);this.sun.intensity=cfg.sun;this.ambient.intensity=cfg.ambient;this.renderer.toneMappingExposure=cfg.exposure;const direction=new THREE.Vector3().setFromSphericalCoords(1,THREE.MathUtils.degToRad(90-cfg.elevation),THREE.MathUtils.degToRad(cfg.azimuth));this.sky.material.uniforms.sunPosition.value.copy(direction);this.sunDirection=direction;this.sky.visible=mode==='golden'||mode==='day';this.scene.background=new THREE.Color(cfg.color);this.rain.visible=mode==='rain';this.materials.road.roughness=mode==='rain'?.16:.9;this.materials.road.color.set(mode==='rain'?'#303e48':'#666a70');this.lampMat.emissiveIntensity=mode==='night'?5:mode==='rain'||mode==='fog'?1:.05;}
 setPhoto(on){this.photo=on;this.orbit.yaw=.7;this.orbit.pitch=.3;this.orbit.distance=11;}
 update(sim,dt,playing){this.clock+=dt;const car=sim.vehicle,body=car.body;for(const record of [car,...sim.traffic]){let visual=this.carVisuals.get(record);if(!visual){visual=this.createCar(record===car?'#bc8050':['#b4c4ce','#704e46','#a4ad9c'][this.carVisuals.size%3],record===car);this.carVisuals.set(record,visual);}visual.root.position.copy(record.body.position);visual.root.quaternion.copy(record.body.quaternion);for(let i=0;i<4;i++){const info=record.raycast.wheelInfos[i];if(info.worldTransform){visual.wheels[i].position.copy(info.worldTransform.position);visual.wheels[i].quaternion.copy(info.worldTransform.quaternion);}}visual.lamps.forEach(l=>l.intensity=this.weather==='night'?85:this.weather==='rain'||this.weather==='fog'?25:0);visual.taillight.emissiveIntensity=sim.controls.brake>0?4:1;visual.steering.rotation.z=-sim.controls.steer*.6;if(record===car){visual.root.visible=true;visual.cabin.visible=this.mode!==1||this.photo;visual.paint.roughness=.24+(1-(record.health??1))*.5;}}
 const bp=new THREE.Vector3().copy(body.position),q=new THREE.Quaternion().copy(body.quaternion);const heading=new THREE.Vector3(0,0,-1).applyQuaternion(q);heading.y=0;heading.normalize();const yaw=Math.atan2(-heading.x,-heading.z);let desired,look;if(this.photo||!playing){const o=this.orbit;if(!playing)o.yaw=this.clock*.045+.4;desired=bp.clone().add(new THREE.Vector3(Math.sin(o.yaw)*Math.cos(o.pitch)*o.distance,Math.sin(o.pitch)*o.distance+1.1,Math.cos(o.yaw)*Math.cos(o.pitch)*o.distance));look=bp.clone().addScaledVector(UP,.5);}else if(this.mode===1){desired=bp.clone().add(new THREE.Vector3(-.37,.76,.25).applyQuaternion(q));look=desired.clone().add(new THREE.Vector3(0,0,-25).applyQuaternion(q));}else if(this.mode===2){desired=bp.clone().add(new THREE.Vector3(Math.sin(this.clock*.12)*14,6,Math.cos(this.clock*.12)*14));look=bp.clone().addScaledVector(UP,.6);}else{desired=bp.clone().addScaledVector(heading,-8.5-Math.min(sim.speedKph/80,2)).addScaledVector(UP,3.5);look=bp.clone().addScaledVector(heading,6).addScaledVector(UP,.7);}desired.y=Math.max(desired.y,terrainHeight(this.city,desired.x,-desired.z)+.7);if(this.mode===1&&!this.photo)this.camera.position.copy(desired);else this.camera.position.lerp(desired,1-Math.exp(-dt*5));this.camera.lookAt(look);this.camera.fov=this.mode===1?75:this.photo?45:55+Math.min(sim.speedKph/20,8);this.camera.updateProjectionMatrix();this.sun.position.copy(bp).addScaledVector(this.sunDirection,300);this.sun.target.position.copy(bp);this.sun.target.updateMatrixWorld();if(this.weather==='night'||this.weather==='rain'){const closest=[...this.lightPosts].sort((a,b)=>a.distanceToSquared(bp)-b.distanceToSquared(bp));for(let i=0;i<this.nearLights.length;i++){if(closest[i])this.nearLights[i].position.copy(closest[i]);this.nearLights[i].intensity=this.weather==='night'?18:5;}}else this.nearLights.forEach(l=>l.intensity=0);if(this.rain.visible){this.rain.position.copy(bp);const p=this.rain.geometry.attributes.position;for(let i=0;i<p.count;i++){p.setY(i,(p.getY(i)-dt*32+80)%80);p.setX(i,(p.getX(i)-dt*3+150)%100-50);}p.needsUpdate=true;}this.renderer.render(this.scene,this.camera);}
 screenshot(){this.renderer.render(this.scene,this.camera);const a=document.createElement('a');a.download=`city-wheels-${this.weather}.png`;a.href=this.renderer.domElement.toDataURL('image/png');a.click();}
}
